-- CREATE DATABASE Customer_Behavior;
USE Customer_Behavior;
SELECT * FROM customer LIMIT 20;
SHOW tables;

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT GENDER,SUM(purchase_amount) AS revenue
from customer
GROUP BY gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied='Yes' AND purchase_amount >(SELECT AVG (purchase_amount) FROM customer);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT ROUND(AVG (review_rating),2) AS avg_rating, item_purchased AS product
FROM customer
GROUP BY product
ORDER BY avg_rating  DESC
LIMIT 5 ;


SELECT*FROM customer;	
-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT AVG(purchase_amount),Shipping_type
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT COUNT(customer_id) AS total_customers, 
subscription_status, AVG(purchase_amount) AS avg_spend , SUM(purchase_amount) AS total_revenue
FROM customer
-- WHERE subscription_status in('YES', 'NO')
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased ,
ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 END)/COUNT(*) * 100,2) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate desc
LIMIT 5 ;

 
-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
   SELECT 

    CASE 
        WHEN previous_purchases = 0 THEN 'new'
        WHEN previous_purchases BETWEEN 1 AND 3 THEN 'returning'
        WHEN previous_purchases > 3 THEN 'loyal'
    END AS segement,
    COUNT(customer_id)
FROM customer
GROUP BY segement;


SELECT*FROM customer;
-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts as (
SELECT category, item_purchased,
COUNT(customer_id) AS Total_orders,
ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id)DESC) as item_rank 
FROM customer 
GROUP BY category,item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, 
COUNT(customer_id) AS repeat_buyers
FROM customer 
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. What is the revenue contribution of each age group?
SELECT age_group,
SUM(purchase_amount) AS Total_revenue
FROM customer
GROUP BY age_group
ORDER BY Total_revenue DESC;